### ISSUE TITLE
update wiki

### ISSUE THREAD

**Issue by iamgurdip** [sergeyzwezdin/cqrs-spirit#1]
Let me first say thank you for sharing this. It would be great if you can update the project and the wiki.

Thank you.

**Comment by sergeyzwezdin** [comment]
@iamgurdip I don't think such tiny library really needs wiki. I've added some explanation into `readme.md` as well as created [demo project](https://github.com/sergeyzwezdin/cqrs-spirit/tree/master/sources/SampleWebApp). Feel free to ask any questions you have.
